import type { Dispatch, SetStateAction } from 'react';
import type { AgentBlueprint, AgentSpec, AgentToolSpec, HandoffSpec } from '../types';
import { OptionalNumber } from './InspectorFields';

export function AgentRelationships({
  blueprint,
  setBlueprint,
  agent,
}: {
  blueprint: AgentBlueprint;
  setBlueprint: Dispatch<SetStateAction<AgentBlueprint>>;
  agent: AgentSpec;
}) {
  const candidates = blueprint.agents.filter((item) => item.id !== agent.id);
  const addHandoff = (target: string) =>
    setBlueprint((current) => ({
      ...current,
      handoffs: [...(current.handoffs ?? []), {
        id: `handoff-${agent.id}-${target}`,
        source_agent_id: agent.id,
        target_agent_id: target,
        tool_name: null,
        tool_description: null,
        nest_handoff_history: null,
      }],
    }));
  const addAgentTool = (delegate: string) =>
    setBlueprint((current) => ({
      ...current,
      agent_tools: [...(current.agent_tools ?? []), {
        id: `agent-tool-${agent.id}-${delegate}`,
        owner_agent_id: agent.id,
        delegate_agent_id: delegate,
        tool_name: `ask_${delegate.split('-').join('_')}`,
        tool_description: `Ask ${delegate} to handle a focused subtask.`,
        max_turns: null,
        needs_approval: false,
      }],
    }));
  if (!candidates.length) return null;
  return (
    <div className="stack">
      <h3>Relationships</h3>
      {candidates.map((candidate) => {
        const hasHandoff = (blueprint.handoffs ?? []).some(
          (relation) =>
            relation.source_agent_id === agent.id &&
            relation.target_agent_id === candidate.id,
        );
        const hasAgentTool = (blueprint.agent_tools ?? []).some(
          (relation) =>
            relation.owner_agent_id === agent.id &&
            relation.delegate_agent_id === candidate.id,
        );
        return (
          <div className="relationship-row" key={candidate.id}>
            <span>{candidate.name}</span>
            <button type="button" className="button secondary small" disabled={hasHandoff} onClick={() => addHandoff(candidate.id)}>Handoff</button>
            <button type="button" className="button secondary small" disabled={hasAgentTool} onClick={() => addAgentTool(candidate.id)}>As tool</button>
          </div>
        );
      })}
    </div>
  );
}

export function HandoffInspector({
  blueprint,
  setBlueprint,
  relation,
  onRemove,
}: {
  blueprint: AgentBlueprint;
  setBlueprint: Dispatch<SetStateAction<AgentBlueprint>>;
  relation: HandoffSpec;
  onRemove: () => void;
}) {
  const update = (patch: Partial<HandoffSpec>) =>
    setBlueprint((current) => ({
      ...current,
      handoffs: (current.handoffs ?? []).map((item) =>
        item.id === relation.id ? { ...item, ...patch } : item,
      ),
    }));
  return (
    <div className="inspector stack">
      <div className="inspector-heading">
        <div><span className="eyebrow">SDK handoff</span><h2>{relation.id}</h2></div>
        <button className="button small danger" type="button" onClick={onRemove}>Remove</button>
      </div>
      <RelationshipAgents
        blueprint={blueprint}
        sourceLabel="Source agent"
        source={relation.source_agent_id}
        targetLabel="Target agent"
        target={relation.target_agent_id}
        onSourceChange={(source_agent_id) => update({ source_agent_id })}
        onTargetChange={(target_agent_id) => update({ target_agent_id })}
      />
      <label className="field">Tool name<input value={relation.tool_name ?? ''} placeholder="Generated by SDK" onChange={(event) => update({ tool_name: event.target.value || null })} /></label>
      <label className="field">Tool description<textarea value={relation.tool_description ?? ''} placeholder="Generated by SDK" onChange={(event) => update({ tool_description: event.target.value || null })} /></label>
      <label className="field">
        Nested handoff history
        <select value={relation.nest_handoff_history == null ? '' : String(relation.nest_handoff_history)} onChange={(event) => update({ nest_handoff_history: event.target.value === '' ? null : event.target.value === 'true' })}>
          <option value="">SDK default</option>
          <option value="true">Enabled</option>
          <option value="false">Disabled</option>
        </select>
      </label>
    </div>
  );
}

export function AgentToolInspector({
  blueprint,
  setBlueprint,
  relation,
  onRemove,
}: {
  blueprint: AgentBlueprint;
  setBlueprint: Dispatch<SetStateAction<AgentBlueprint>>;
  relation: AgentToolSpec;
  onRemove: () => void;
}) {
  const update = (patch: Partial<AgentToolSpec>) =>
    setBlueprint((current) => ({
      ...current,
      agent_tools: (current.agent_tools ?? []).map((item) =>
        item.id === relation.id ? { ...item, ...patch } : item,
      ),
    }));
  return (
    <div className="inspector stack">
      <div className="inspector-heading">
        <div><span className="eyebrow">Agent.as_tool</span><h2>{relation.tool_name}</h2></div>
        <button className="button small danger" type="button" onClick={onRemove}>Remove</button>
      </div>
      <RelationshipAgents
        blueprint={blueprint}
        sourceLabel="Owner agent"
        source={relation.owner_agent_id}
        targetLabel="Delegate agent"
        target={relation.delegate_agent_id}
        onSourceChange={(owner_agent_id) => update({ owner_agent_id })}
        onTargetChange={(delegate_agent_id) => update({ delegate_agent_id })}
      />
      <label className="field">Tool name<input value={relation.tool_name} onChange={(event) => update({ tool_name: event.target.value })} /></label>
      <label className="field">Tool description<textarea value={relation.tool_description} onChange={(event) => update({ tool_description: event.target.value })} /></label>
      <OptionalNumber label="Maximum nested turns" value={relation.max_turns} min={1} max={100} onChange={(max_turns) => update({ max_turns })} />
      <label className="check-row"><input type="checkbox" checked={relation.needs_approval} onChange={(event) => update({ needs_approval: event.target.checked })} />Require approval</label>
    </div>
  );
}

function RelationshipAgents({
  blueprint,
  sourceLabel,
  source,
  targetLabel,
  target,
  onSourceChange,
  onTargetChange,
}: {
  blueprint: AgentBlueprint;
  sourceLabel: string;
  source: string;
  targetLabel: string;
  target: string;
  onSourceChange: (id: string) => void;
  onTargetChange: (id: string) => void;
}) {
  return (
    <div className="field-row">
      <label className="field">
        {sourceLabel}
        <select value={source} onChange={(event) => onSourceChange(event.target.value)}>
          {blueprint.agents
            .filter((agent) => agent.id !== target)
            .map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}
        </select>
      </label>
      <label className="field">
        {targetLabel}
        <select value={target} onChange={(event) => onTargetChange(event.target.value)}>
          {blueprint.agents
            .filter((agent) => agent.id !== source)
            .map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}
        </select>
      </label>
    </div>
  );
}
